name: Publish to TigYog.app
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g tigyog-cli
      - run: tigyog login "${TY_SESSION}"
        env:
          TY_SESSION: ${{ secrets.TY_SESSION }}
      - run: tigyog publish src
