name: Publish to TigYog.app
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - env:
          TY_SESSION: ${{ secrets.TY_SESSION }}
        if: ${{ env.TY_SESSION == '' }}
        run: |
          echo "You need to set secret TY_SESSION to your TigYog session token; see https://github.com/tigyog/tigyog-cli"
          exit 1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - run: npx tigyog login "${TY_SESSION}"
        env:
          TY_SESSION: ${{ secrets.TY_SESSION }}
      - run: npm run fmt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: tigyog fmt
      - run: npm run publish
